/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new account
         * @description Creates a user with its primary address. Responds 201 with an empty body. `address.province` = a province `codename` from GET /provinces; `address.ward` = a ward `codename` of that province from GET /provinces/{provinceCode}/wards. Unknown codenames, or a ward of another province, return USER_LOCATION_INVALID.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with identifier and password
         * @description Responds 200 with an access token (JWT), a refresh token and the user profile (same shape as GET /users/me: `email` / `phone` login identifier, `bussinessLicense` signed URL). Unknown identifier, login type mismatch and wrong password all return USER_INVALID_CREDENTIALS. USER_NOT_ACTIVE (distributor not activated yet) is returned only after the password matched.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new token pair
         * @description Responds 200 with a new access token and a new refresh token; the one sent stops working. A just-rotated token sent again within the grace period (retry) still succeeds. Reusing a rotated token after the grace period, or a revoked one, revokes every token of that login. Unknown, expired, reused or revoked tokens and inactive owners all return USER_INVALID_REFRESH_TOKEN.
         */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Revokes the session (every refresh token of that login) the given refresh token belongs to. Responds 200 with an empty body, also when the refresh token is unknown, expired, already revoked or another user's (then nothing changes). The access token stays valid until it expires; discard it.
         */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the password of the caller
         * @description Requires the current password. Responds 200 with an empty body. Every session of the user ends (all refresh tokens revoked); access tokens already issued stay valid until they expire. A wrong current password returns 400 USER_WRONG_PASSWORD and changes nothing.
         */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/realtime-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a realtime ticket for the caller
         * @description For browsers behind a BFF that must not hold the access token: the BFF calls this with the access token and hands only the ticket to the browser, which opens the socket.io connection with `auth: { ticket }`. The ticket expires after `expiresIn` seconds (default 30) and only needs to be valid at the handshake; fetch a new one for every connect/reconnect. It is not accepted as an access token. An invalid or expired ticket fails the handshake with connect_error AUTH_INVALID_ACCESS_TOKEN.
         */
        post: operations["AuthController_realtimeTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the profile of the caller
         * @description Profile as returned by POST /auth/login (user), including the primary address (null if none). `email` / `phone`: the login identifier (the other one is null). `bussinessLicense`: signed read URL of the business license (expires; null if none). Works for any user with a valid access token, whatever its status.
         */
        get: operations["UserController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update the profile of the caller
         * @description Every field is optional; an absent or null field is kept (clearing avatar / business license is not supported). bussinessType: DISTRIBUTOR only, cannot be set to null. avatar / bussinessLicense: a file already uploaded to TMP (key from POST /media/presign-url). The response returns its new media id at once; the file is moved and the previous one deleted in the background. An invalid or missing TMP file is skipped (logged) and the previous file is kept, but the returned media id is still stored.
         */
        patch: operations["UserController_updateMe"];
        trace?: never;
    };
    "/users/me/addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the addresses of the caller
         * @description Every address of the caller, primary first. Works for any user with a valid access token, whatever its status.
         */
        get: operations["UserController_getMyAddresses"];
        put?: never;
        /**
         * Add an address for the caller
         * @description Responds 201 with the new address id. `province` = a province `codename` from GET /provinces; `ward` = a ward `codename` of that province from GET /provinces/{provinceCode}/wards. `isPrimary` (default false): true makes it the primary address and the current primary becomes a normal one.
         */
        post: operations["UserController_createMyAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/addresses/{addressId}/primary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set one of the caller's addresses as primary
         * @description The current primary becomes a normal address. Already primary: 200, nothing changes. An address of another user answers 404 like an unknown one.
         */
        patch: operations["UserController_setMyPrimaryAddress"];
        trace?: never;
    };
    "/users/me/addresses/{addressId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete one of the caller's addresses
         * @description Hard delete. The primary address cannot be deleted: set another address as primary first (PATCH /users/me/addresses/{addressId}/primary), so a user always keeps one. An address of another user answers 404 like an unknown one.
         */
        delete: operations["UserController_deleteMyAddress"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributors/nearby": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List distributors near a location (public)
         * @description No login needed; the access token is optional (an invalid one → 401). Location, first match wins: `lat` + `long` (GPS or a point picked on the map); `provinceCode` [+ `wardCode`] (codenames from GET /provinces and GET /provinces/{provinceCode}/wards); none: the caller's primary address (guest, or no address: every distributor by username). A point and an area cannot be combined. Stages run in order and the first one with any distributor is paginated — point: `radius` (within DISTRIBUTOR_SEARCH_RADIUS_KM, default 30 km) → `nationwide_by_distance`, nearest first; area: `province` (the given ward first, then by username) → `nationwide`, by username. `scope` names the stage, `source` where the location came from. `distanceMeters` is set for the distance scopes only. Only ACTIVE distributors are listed, at their primary address. No match at all: 200 with empty `items`.
         */
        get: operations["DistributorController_findNearby"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/distributors/{distributorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the public profile of a distributor (public)
         * @description No login needed. Returns the distributor with its primary address (null if none); the full address list is GET /users/me/addresses (owner only). `email` / `phone`: the login identifier (the other one is null). `bussinessLicense`: signed read URL of the business license (expires; null if none). `avatar` is a media id. Unknown id, not a DISTRIBUTOR, or not ACTIVE → 404 USER_DISTRIBUTOR_NOT_FOUND.
         */
        get: operations["DistributorController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all provinces
         * @description Public (no login). Every province in master data order, not paginated. Use `codename` as `provinceCode` for GET /provinces/{provinceCode}/wards.
         */
        get: operations["LocationController_listAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provinces/{provinceCode}/wards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the wards of a province
         * @description Public (no login). Every ward of the province in master data order, not paginated. `provinceCode` = a province `codename` (lowercase letters, digits, `_`; max 64). Ward `codename` is unique within its province only.
         */
        get: operations["LocationController_listWards"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/presign-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get signed URLs to upload 1..10 files to TMP storage
         * @description Send 1..10 `files`; returns one `items` entry per file, in the same order. Allowed extensions: IMAGE jpg/jpeg/png/webp, VIDEO mp4/mov, FILE pdf (case-insensitive, leading dot ignored). All-or-nothing: if any file has an extension not allowed for its type, responds 400 `MEDIA_INVALID_EXTENSION` with `details.files: [{ index, type, extension, allowed }]` listing every invalid file, and no URL is issued. Upload each file with `PUT <presignUrl>` sending exactly its `headers` (Content-Type and `x-goog-content-length-range`); the storage rejects a different Content-Type, a file over 10 MB, or an expired URL. Keep each `key` to confirm the upload later.
         */
        post: operations["MediaController_presignUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate a DISTRIBUTOR account with the code sent at registration
         * @description Checks the latest activation code of the identifier (email or phone, any format). A wrong code is counted; too many wrong codes block the code for a while (OTP_BLOCKED). Responds 200 with an empty body; the account becomes ACTIVE.
         */
        post: operations["ActivationController_activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send the activation or password reset code again
         * @description `purpose` picks the code: ACTIVATE_DISTRIBUTOR (sent at registration) or RESET_PASSWORD (sent by POST /auth/reset-password). Sends the latest code of that purpose again while it is valid; each resend is counted and too many resends block the code for a while (OTP_BLOCKED, details { blockUntil }). If the code expired (and is not blocked) a new code is issued and sent. OTP_NOT_FOUND when the identifier is unknown or no code of that purpose was sent. Responds 200 with an empty body.
         */
        post: operations["ActivationController_resend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a password reset code
         * @description Sends a RESET_PASSWORD code by email or SMS (per loginType) to an ACTIVE account. Responds 200 with an empty body. While the previous reset code is still valid: 409 OTP_ALREADY_REQUESTED, details { purpose, issuedAt, expiredAt }. While it is blocked (too many wrong codes), even if expired: 422 OTP_BLOCKED, details { blockUntil }. Once the previous code is expired or used, a new code is sent.
         */
        post: operations["PasswordResetController_requestReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a new password with the reset code
         * @description Checks the latest RESET_PASSWORD code of the identifier (email or phone, any format) and consumes it. A wrong code is counted; too many wrong codes block the code for a while (OTP_BLOCKED, details { blockUntil }). Responds 200 with an empty body: the password is replaced and every session of the user is logged out (refresh tokens revoked).
         */
        post: operations["PasswordResetController_confirmReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a distributor's products (public)
         * @description No login needed. Lists the ACTIVE, not deleted products of `distributorId`, newest first (INACTIVE / OUT_OF_STOCK are hidden). `limit` 1..50, default 20. To get the next page pass the returned `nextCursor` as `cursor` (same `distributorId`); `nextCursor` is null on the last page. `thumbnail` is a signed URL of the first image (expires after the configured TTL, default 1h), or null when the product has no image. `distributorId` that is not a DISTRIBUTOR → 404.
         */
        get: operations["ProductController_listByDistributor"];
        put?: never;
        /**
         * Create a product (ACTIVE distributor only)
         * @description Caller must be a DISTRIBUTOR whose account is ACTIVE, otherwise 403 `PRODUCT_SELLER_NOT_ALLOWED`. `categoryId` comes from `GET /categories`. `price` >= 0 with at most 2 decimals; `quantity` integer >= 0. Upload files first: `POST /media/presign-url`, PUT each file to its URL, then send 1..10 `media` items with the returned `key` and the same `type`/`extension`. The product is created ACTIVE and each file is moved out of TMP and attached to it. A media item that cannot be attached (key of another user, extension mismatch, file not uploaded) is skipped and logged; the product is still created.
         */
        post: operations["ProductController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a product detail (public)
         * @description No login needed. Returns the product in any status (ACTIVE / INACTIVE / OUT_OF_STOCK) with its seller `distributorId` and every media (IMAGE / VIDEO / FILE) ordered by `sortOrder`. Each `url` is a signed URL (expires after the configured TTL, default 1h). A deleted product → 404. Rating: `GET /reviews/summary`.
         */
        get: operations["ProductController_getDetail"];
        put?: never;
        post?: never;
        /**
         * Delete own product (ACTIVE distributor only)
         * @description Caller must be a DISTRIBUTOR whose account is ACTIVE (else 403 `PRODUCT_SELLER_NOT_ALLOWED`) and the seller of the product (else 403 `PRODUCT_NOT_OWNER`). Soft delete: the product is kept for history but treated as missing afterwards (update/delete → 404 `PRODUCT_NOT_FOUND`). All its media (records and stored files) are removed. Returns an empty body.
         */
        delete: operations["ProductController_delete"];
        options?: never;
        head?: never;
        /**
         * Update own product (ACTIVE distributor only)
         * @description Caller must be a DISTRIBUTOR whose account is ACTIVE (else 403 `PRODUCT_SELLER_NOT_ALLOWED`) and the seller of the product (else 403 `PRODUCT_NOT_OWNER`). Every field is optional: omitted fields keep their value, `null` is rejected. Same rules as create for `price`, `quantity`, `unit`, `categoryId`; `status` is ACTIVE | INACTIVE | OUT_OF_STOCK. `addMedia` (0..10): files uploaded via `POST /media/presign-url`, moved out of TMP and attached; an item that cannot be attached is skipped and logged. `removeMediaIds` (0..10): media of this product to delete (record and stored file); ids of other products are ignored. Returns an empty body.
         */
        patch: operations["ProductController_update"];
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List product categories, ordered by name */
        get: operations["CategoryController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reviews of a distributor's shop (public)
         * @description No login needed. Lists reviews of the distributor itself (USER) and of every product it ever listed (PRODUCT; any status, deleted products included), newest first. Filter with `targetType` and/or `star`. `summary` covers every review of the shop and is not affected by filters or cursor; `avgRating` has 1 decimal and is 0 when there is no review. `limit` 1..50, default 20. To get the next page pass the returned `nextCursor` as `cursor` with the same filters; `nextCursor` is null on the last page. `productName` is null for shop (USER) reviews. `user.avatar` is a signed URL (expires after the configured TTL, default 1h), or null. `distributorId` that is not a DISTRIBUTOR → 404.
         */
        get: operations["ReviewController_listByDistributor"];
        put?: never;
        /**
         * Review a distributor or one of its products (ACTIVE farmer only)
         * @description Caller must be a FARMER whose account is ACTIVE, otherwise 403 `REVIEW_REVIEWER_NOT_ALLOWED`. `targetType` USER: `targetId` is a distributor user id; it must be an ACTIVE DISTRIBUTOR. `targetType` PRODUCT: `targetId` is a product id; the product must be ACTIVE (deleted → 404, INACTIVE / OUT_OF_STOCK → 422). A farmer reviews each target once (second time → 409). `star` integer 1..5; `content` 1..1000 characters after trimming. On success the distributor (the shop itself, or the seller of the product) gets a REVIEW notification with `referenceId` = `reviewId`.
         */
        post: operations["ReviewController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the rating of a product or a distributor (public)
         * @description No login needed. `targetType=PRODUCT`: reviews of that product. `targetType=USER`: reviews of the distributor itself only (not of its products; the whole shop summary is in `GET /reviews`). `avgRating` has 1 decimal and is 0 when there is no review. A target without reviews, or that does not exist, returns all zero.
         */
        get: operations["ReviewController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List reviews of a product (public)
         * @description No login needed. Reviews of one product (any status; a deleted or unknown product → 404), newest first. Filter with `star`. `limit` 1..50, default 20. To get the next page pass the returned `nextCursor` as `cursor` with the same `star`; `nextCursor` is null on the last page. `user.avatar` is a signed URL (expires after the configured TTL, default 1h), or null. Rating of the product: `GET /reviews/summary`.
         */
        get: operations["ReviewController_listByProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit own review (ACTIVE farmer only)
         * @description Caller must be a FARMER whose account is ACTIVE, otherwise 403 `REVIEW_REVIEWER_NOT_ALLOWED`. Only the author may edit the review (else 403 `REVIEW_NOT_OWNER`). Works for shop (USER) and product (PRODUCT) reviews; the target is not re-checked. Omitted fields keep their value; `null` is rejected. `star` integer 1..5; `content` 1..1000 characters after trimming. Empty body → 200, nothing changes. On change the distributor (the shop itself, or the seller of the product) gets a REVIEW notification with `referenceId` = `reviewId` (none if the product was deleted). Response body is null.
         */
        patch: operations["ReviewController_update"];
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's notifications
         * @description Any logged-in user. Returns only notifications addressed to the caller (read and unread), newest first. `limit` 1..50, default 20. To get the next page pass the returned `nextCursor` as `cursor`; `nextCursor` is null on the last page. For type REVIEW, `referenceId` is the review id. Realtime: while connected to the socket (`io(url, { auth: { token } })`), each new notification is also pushed as socket event `notification.created` with the same item shape (createdAt as ISO string), to every open connection of the recipient. Offline recipients get no push; they see it here.
         */
        get: operations["NotificationController_listMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark all of the caller's notifications as read
         * @description Marks every unread notification of the caller as read. Empty body on success; also 200 when there is nothing to mark.
         */
        patch: operations["NotificationController_markAllRead"];
        trace?: never;
    };
    "/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark one of the caller's notifications as read
         * @description Empty body on success; already read → 200, no change. A notification of another user → 404, same as a missing one.
         */
        patch: operations["NotificationController_markRead"];
        trace?: never;
    };
    "/chat/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's chat rooms with unread counts
         * @description Any logged-in user. Rooms the caller is a member of, most recent message first (`lastMessageAt` desc). Each room carries the other member: `otherUserId`, `otherUsername` (null if that user no longer exists) and `otherUserAvatar` (signed read URL that expires; null when none). `unreadCount` = messages from the other member not read by the caller; a message is read when it arrives while the caller has the room open (socket `chat.room.enter`), or once the caller enters the room later. The caller’s own messages never count. `totalUnread` covers all rooms, not only this page. `limit` 1..50, default 20; pass the returned `nextCursor` as `cursor` for the next page (null on the last page).
         */
        get: operations["ChatController_listMyRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/rooms/{roomId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the messages of a chat room
         * @description Caller must be a member of the room. Newest message first (`createdAt` desc); `limit` 1..50, default 20; pass the returned `nextCursor` as `cursor` to get older messages (null on the last page). Each message carries its sender's `senderUsername` (null when the user no longer exists) and `senderAvatar` (signed read URL that expires; null when none). Read-only: does not mark messages read (socket `chat.room.enter` does). New messages arrive live through socket `chat.message.received` (same sender fields).
         */
        get: operations["ChatController_listMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DomainErrorResponse: {
            /** @example 409 */
            statusCode: number;
            /** @example USER_IDENTIFIER_ALREADY_USED */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ValidationErrorResponse: {
            /** @example 400 */
            statusCode: number;
            /**
             * @example [
             *       "password must be longer than or equal to 8 characters"
             *     ]
             */
            message: string[];
            /** @example Bad Request */
            error: string;
        };
        RegisterAddressDto: {
            province: string;
            ward: string;
            houseNumber: string;
            lat: number;
            long: number;
            isPrimary?: boolean;
        };
        RegisterUserDto: {
            /** @enum {string} */
            loginType: "EMAIL" | "PHONE";
            identifier: string;
            password: string;
            username?: string;
            /** @enum {string} */
            role: "FARMER" | "DISTRIBUTOR";
            /** @enum {string|null} */
            bussinessType?: "AGRICULTURAL_CHEMICAL_SUPPLIES" | "SEEDS_SEEDLINGS" | "AQUACULTURE_SEEDLINGS" | null;
            bio?: string;
            address: components["schemas"]["RegisterAddressDto"];
        };
        LoginUserDto: {
            /** @enum {string} */
            loginType: "EMAIL" | "PHONE";
            identifier: string;
            password: string;
        };
        UserAddressResponse: {
            province: string;
            ward: string;
            houseNumber: string;
            lat: number;
            long: number;
        };
        UserProfileResponse: {
            id: string;
            /** @enum {string} */
            loginType: "EMAIL" | "PHONE";
            email: string | null;
            phone: string | null;
            username: string;
            /** @enum {string} */
            role: "FARMER" | "DISTRIBUTOR";
            /** @enum {string|null} */
            bussinessType: "AGRICULTURAL_CHEMICAL_SUPPLIES" | "SEEDS_SEEDLINGS" | "AQUACULTURE_SEEDLINGS" | null;
            bussinessLicense: string | null;
            avatar: string | null;
            bio: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            address: components["schemas"]["UserAddressResponse"] | null;
        };
        LoginUserResponse: {
            accessToken: string;
            refreshToken: string;
            user: components["schemas"]["UserProfileResponse"];
        };
        RefreshAccessTokenDto: {
            refreshToken: string;
        };
        RefreshAccessTokenResponse: {
            accessToken: string;
            refreshToken: string;
        };
        LogoutUserDto: {
            refreshToken: string;
        };
        ChangePasswordDto: {
            oldPassword: string;
            newPassword: string;
        };
        IssueRealtimeTicketResponse: {
            ticket: string;
            expiresIn: number;
        };
        MyAddressResponse: {
            id: string;
            province: string;
            ward: string;
            houseNumber: string;
            lat: number;
            long: number;
            isPrimary: boolean;
        };
        ListMyAddressesResponse: {
            addresses: components["schemas"]["MyAddressResponse"][];
        };
        CreateAddressDto: {
            province: string;
            ward: string;
            houseNumber: string;
            lat: number;
            long: number;
            isPrimary?: boolean;
        };
        CreateAddressResponse: {
            addressId: string;
        };
        AvatarFileDto: {
            /** @enum {string} */
            type: "IMAGE";
            key: string;
            extension: string;
            filename: string;
        };
        BusinessLicenseFileDto: {
            /** @enum {string} */
            type: "IMAGE" | "FILE";
            key: string;
            extension: string;
            filename: string;
        };
        UpdateProfileDto: {
            username?: string;
            bio?: string;
            /** @enum {string|null} */
            bussinessType?: "AGRICULTURAL_CHEMICAL_SUPPLIES" | "SEEDS_SEEDLINGS" | "AQUACULTURE_SEEDLINGS" | null;
            avatar?: components["schemas"]["AvatarFileDto"] | null;
            bussinessLicense?: components["schemas"]["BusinessLicenseFileDto"] | null;
        };
        UpdateProfileResponse: {
            username: string;
            avatar: string | null;
            bio: string | null;
            bussinessLicense: string | null;
            /** @enum {string|null} */
            bussinessType: "AGRICULTURAL_CHEMICAL_SUPPLIES" | "SEEDS_SEEDLINGS" | "AQUACULTURE_SEEDLINGS" | null;
            /** Format: date-time */
            updatedAt: string;
        };
        NearbyDistributorAddressResponse: {
            province: string;
            ward: string;
            houseNumber: string;
            lat: number;
            long: number;
        };
        NearbyDistributorResponse: {
            userId: string;
            username: string;
            avatar: string | null;
            /** @enum {string|null} */
            bussinessType: "AGRICULTURAL_CHEMICAL_SUPPLIES" | "SEEDS_SEEDLINGS" | "AQUACULTURE_SEEDLINGS" | null;
            address: components["schemas"]["NearbyDistributorAddressResponse"];
            distanceMeters: number | null;
        };
        FindNearbyDistributorsResponse: {
            /** @enum {string} */
            scope: "radius" | "nationwide_by_distance" | "province" | "nationwide";
            /** @enum {string} */
            source: "query_point" | "query_area" | "address" | "none";
            items: components["schemas"]["NearbyDistributorResponse"][];
            total: number;
        };
        DistributorProfileResponse: {
            id: string;
            email: string | null;
            phone: string | null;
            username: string;
            avatar: string | null;
            bio: string | null;
            /** @enum {string|null} */
            bussinessType: "AGRICULTURAL_CHEMICAL_SUPPLIES" | "SEEDS_SEEDLINGS" | "AQUACULTURE_SEEDLINGS" | null;
            bussinessLicense: string | null;
            /** Format: date-time */
            createdAt: string;
            address: components["schemas"]["UserAddressResponse"] | null;
        };
        LocationItemResponse: {
            codename: string;
            name: string;
        };
        ListProvincesResponse: {
            provinces: components["schemas"]["LocationItemResponse"][];
        };
        ListWardsResponse: {
            wards: components["schemas"]["LocationItemResponse"][];
        };
        PresignFileDto: {
            filename: string;
            extension: string;
            /** @enum {string} */
            type: "IMAGE" | "VIDEO" | "FILE";
        };
        GetPresignUrlDto: {
            files: components["schemas"]["PresignFileDto"][];
        };
        PresignedMediaResponse: {
            presignUrl: string;
            key: string;
            headers: Record<string, never>;
        };
        GetPresignUrlResponse: {
            items: components["schemas"]["PresignedMediaResponse"][];
        };
        ActivateAccountDto: {
            identifier: string;
            code: string;
        };
        ResendCodeDto: {
            identifier: string;
            /** @enum {string} */
            purpose: "ACTIVATE_DISTRIBUTOR" | "RESET_PASSWORD";
        };
        RequestPasswordResetDto: {
            /** @enum {string} */
            loginType: "EMAIL" | "PHONE";
            identifier: string;
        };
        ConfirmPasswordResetDto: {
            identifier: string;
            code: string;
            newPassword: string;
        };
        DistributorProductResponse: {
            id: string;
            name: string;
            price: number;
            quantity: number;
            /** @enum {string} */
            unit: "kg" | "10kg" | "50kg" | "100kg" | "bag" | "piece" | "ton";
            thumbnail: string | null;
            distributorId: string;
            distributorName: string;
        };
        ListDistributorProductsResponse: {
            products: components["schemas"]["DistributorProductResponse"][];
            nextCursor: string | null;
        };
        ProductMediaResponse: {
            id: string;
            type: Record<string, never>;
            url: string;
        };
        GetProductDetailResponse: {
            id: string;
            name: string;
            description: string;
            price: number;
            quantity: number;
            /** @enum {string} */
            unit: "kg" | "10kg" | "50kg" | "100kg" | "bag" | "piece" | "ton";
            categoryId: string;
            /** @enum {string} */
            status: "ACTIVE" | "INACTIVE" | "OUT_OF_STOCK";
            distributorId: string;
            media: components["schemas"]["ProductMediaResponse"][];
        };
        ProductMediaDto: {
            key: string;
            /** @enum {string} */
            type: "IMAGE" | "VIDEO" | "FILE";
            extension: string;
            filename: string;
            sortOrder?: number;
        };
        CreateProductDto: {
            name: string;
            description: string;
            price: number;
            categoryId: string;
            quantity: number;
            /** @enum {string} */
            unit: "kg" | "10kg" | "50kg" | "100kg" | "bag" | "piece" | "ton";
            media: components["schemas"]["ProductMediaDto"][];
        };
        CreateProductResponse: {
            productId: string;
        };
        UpdateProductDto: {
            name?: string;
            description?: string;
            price?: number;
            quantity?: number;
            /** @enum {string} */
            unit?: "kg" | "10kg" | "50kg" | "100kg" | "bag" | "piece" | "ton";
            categoryId?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE" | "OUT_OF_STOCK";
            addMedia?: components["schemas"]["ProductMediaDto"][];
            removeMediaIds?: string[];
        };
        CategoryResponse: {
            id: string;
            name: string;
        };
        ListCategoriesResponse: {
            items: components["schemas"]["CategoryResponse"][];
        };
        ReviewStarCountsResponse: {
            1: number;
            2: number;
            3: number;
            4: number;
            5: number;
        };
        ReviewSummaryResponse: {
            avgRating: number;
            reviewCount: number;
            starCounts: components["schemas"]["ReviewStarCountsResponse"];
        };
        ReviewerResponse: {
            id: string;
            username: string | null;
            avatar: string | null;
        };
        DistributorReviewResponse: {
            id: string;
            /** @enum {string} */
            targetType: "PRODUCT" | "USER";
            targetId: string;
            productName: string | null;
            star: number;
            content: string;
            /** Format: date-time */
            createdAt: string;
            user: components["schemas"]["ReviewerResponse"];
        };
        ListDistributorReviewsResponse: {
            summary: components["schemas"]["ReviewSummaryResponse"];
            reviews: components["schemas"]["DistributorReviewResponse"][];
            nextCursor: string | null;
        };
        GetReviewSummaryResponse: {
            avgRating: number;
            reviewCount: number;
            oneStarCount: number;
            twoStarCount: number;
            threeStarCount: number;
            fourStarCount: number;
            fiveStarCount: number;
        };
        ProductReviewResponse: {
            id: string;
            star: number;
            content: string;
            /** Format: date-time */
            createdAt: string;
            user: components["schemas"]["ReviewerResponse"];
        };
        ListProductReviewsResponse: {
            reviews: components["schemas"]["ProductReviewResponse"][];
            nextCursor: string | null;
        };
        CreateReviewDto: {
            /** @enum {string} */
            targetType: "PRODUCT" | "USER";
            targetId: string;
            content: string;
            star: number;
        };
        CreateReviewResponse: {
            reviewId: string;
        };
        UpdateReviewDto: {
            content?: string;
            star?: number;
        };
        NotificationResponse: {
            id: string;
            /** @enum {string} */
            type: "PLATFORM" | "REVIEW";
            label: string;
            content: string;
            isRead: boolean;
            referenceId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ListMyNotificationsResponse: {
            notifications: components["schemas"]["NotificationResponse"][];
            nextCursor: string | null;
        };
        ChatRoomLastMessageResponse: {
            messageId: string;
            senderId: string;
            message: string;
        };
        ChatRoomResponse: {
            roomId: string;
            otherUserId: string;
            otherUsername: string | null;
            otherUserAvatar: string | null;
            lastMessage: components["schemas"]["ChatRoomLastMessageResponse"] | null;
            /** Format: date-time */
            lastMessageAt: string;
            unreadCount: number;
        };
        ListMyChatRoomsResponse: {
            totalUnread: number;
            rooms: components["schemas"]["ChatRoomResponse"][];
            nextCursor: string | null;
        };
        RoomMessageResponse: {
            id: string;
            senderId: string;
            senderUsername: string | null;
            senderAvatar: string | null;
            message: string;
            /** Format: date-time */
            createdAt: string;
        };
        ListRoomMessagesResponse: {
            messages: components["schemas"]["RoomMessageResponse"][];
            nextCursor: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed, or: USER_INVALID_COORDINATES, USER_LOCATION_INVALID, USER_BUSINESS_TYPE_REQUIRED, USER_BUSINESS_TYPE_NOT_ALLOWED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_IDENTIFIER_ALREADY_USED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginUserResponse"];
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description USER_INVALID_CREDENTIALS */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_NOT_ACTIVE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshAccessTokenDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAccessTokenResponse"];
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description USER_INVALID_REFRESH_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed, or: USER_WRONG_PASSWORD */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    AuthController_realtimeTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IssueRealtimeTicketResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_NOT_ACTIVE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    UserController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    UserController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateProfileResponse"];
                };
            };
            /** @description Request validation failed, or: USER_BUSINESS_TYPE_NOT_ALLOWED, USER_BUSINESS_TYPE_REQUIRED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    UserController_getMyAddresses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMyAddressesResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    UserController_createMyAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAddressDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAddressResponse"];
                };
            };
            /** @description Request validation failed, or: USER_INVALID_COORDINATES, USER_LOCATION_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    UserController_setMyPrimaryAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_ADDRESS_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    UserController_deleteMyAddress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                addressId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_ADDRESS_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description USER_ADDRESS_PRIMARY_NOT_DELETABLE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    DistributorController_findNearby: {
        parameters: {
            query?: {
                lat?: number;
                long?: number;
                provinceCode?: string;
                wardCode?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindNearbyDistributorsResponse"];
                };
            };
            /** @description Request validation failed, or: USER_INVALID_COORDINATES, USER_LOCATION_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    DistributorController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                distributorId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributorProfileResponse"];
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description USER_DISTRIBUTOR_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    LocationController_listAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProvincesResponse"];
                };
            };
        };
    };
    LocationController_listWards: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provinceCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListWardsResponse"];
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description LOCATION_PROVINCE_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    MediaController_presignUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetPresignUrlDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetPresignUrlResponse"];
                };
            };
            /** @description Request validation failed, or: MEDIA_INVALID_EXTENSION */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ActivationController_activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivateAccountDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed, or: OTP_INVALID_CODE */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description OTP_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description OTP_ALREADY_CONSUMED, OTP_EXPIRED, OTP_BLOCKED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ActivationController_resend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description OTP_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description OTP_ALREADY_CONSUMED, OTP_BLOCKED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    PasswordResetController_requestReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description OTP_ACCOUNT_NOT_ACTIVE */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description OTP_ACCOUNT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description OTP_ALREADY_REQUESTED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description OTP_BLOCKED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    PasswordResetController_confirmReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPasswordResetDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed, or: OTP_INVALID_CODE */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description OTP_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description OTP_ALREADY_CONSUMED, OTP_EXPIRED, OTP_BLOCKED */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ProductController_listByDistributor: {
        parameters: {
            query: {
                distributorId: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDistributorProductsResponse"];
                };
            };
            /** @description Request validation failed, or: PRODUCT_INVALID_CURSOR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description PRODUCT_DISTRIBUTOR_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ProductController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateProductResponse"];
                };
            };
            /** @description Request validation failed, or: PRODUCT_INVALID_PRICE, PRODUCT_INVALID_QUANTITY */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description PRODUCT_SELLER_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description PRODUCT_CATEGORY_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ProductController_getDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProductDetailResponse"];
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description PRODUCT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ProductController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description PRODUCT_SELLER_NOT_ALLOWED, PRODUCT_NOT_OWNER */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description PRODUCT_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ProductController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed, or: PRODUCT_INVALID_PRICE, PRODUCT_INVALID_QUANTITY */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description PRODUCT_SELLER_NOT_ALLOWED, PRODUCT_NOT_OWNER */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description PRODUCT_NOT_FOUND, PRODUCT_CATEGORY_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    CategoryController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListCategoriesResponse"];
                };
            };
        };
    };
    ReviewController_listByDistributor: {
        parameters: {
            query: {
                distributorId: string;
                targetType?: "PRODUCT" | "USER";
                star?: number;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDistributorReviewsResponse"];
                };
            };
            /** @description Request validation failed, or: REVIEW_INVALID_CURSOR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description REVIEW_DISTRIBUTOR_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ReviewController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReviewDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateReviewResponse"];
                };
            };
            /** @description Request validation failed, or: REVIEW_INVALID_STAR, REVIEW_INVALID_CONTENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description REVIEW_REVIEWER_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description REVIEW_TARGET_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description REVIEW_ALREADY_EXISTS */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description REVIEW_INVALID_TARGET */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ReviewController_summary: {
        parameters: {
            query: {
                targetType: "PRODUCT" | "USER";
                targetId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetReviewSummaryResponse"];
                };
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    ReviewController_listByProduct: {
        parameters: {
            query?: {
                star?: number;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                productId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListProductReviewsResponse"];
                };
            };
            /** @description Request validation failed, or: REVIEW_INVALID_CURSOR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description REVIEW_TARGET_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ReviewController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed, or: REVIEW_INVALID_STAR, REVIEW_INVALID_CONTENT */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description REVIEW_REVIEWER_NOT_ALLOWED, REVIEW_NOT_OWNER */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description REVIEW_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    NotificationController_listMine: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMyNotificationsResponse"];
                };
            };
            /** @description Request validation failed, or: NOTIFICATION_INVALID_CURSOR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    NotificationController_markAllRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    NotificationController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Request validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description NOTIFICATION_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ChatController_listMyRooms: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMyChatRoomsResponse"];
                };
            };
            /** @description Request validation failed, or: CHAT_INVALID_CURSOR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
    ChatController_listMessages: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRoomMessagesResponse"];
                };
            };
            /** @description Request validation failed, or: CHAT_INVALID_CURSOR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"] | components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description AUTH_INVALID_ACCESS_TOKEN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description CHAT_NOT_ROOM_MEMBER */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
            /** @description CHAT_ROOM_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainErrorResponse"];
                };
            };
        };
    };
}
